"""Config-flow tests for companion-plugin pairing credentials."""

from __future__ import annotations

from unittest.mock import AsyncMock, patch

import pytest

pytest.importorskip("homeassistant")
pytest.importorskip("pytest_homeassistant_custom_component")

from homeassistant import config_entries  # noqa: E402
from homeassistant.const import (  # noqa: E402
    CONF_PASSWORD,
    CONF_URL,
    CONF_USERNAME,
)
from homeassistant.core import HomeAssistant  # noqa: E402
from homeassistant.data_entry_flow import FlowResultType  # noqa: E402
from pytest_homeassistant_custom_component.common import (  # noqa: E402
    MockConfigEntry,
)

from custom_components.domoticz_sync import async_migrate_entry  # noqa: E402
from custom_components.domoticz_sync.config_flow import (  # noqa: E402
    DomoticzSyncConfigFlow,
)
from custom_components.domoticz_sync.const import (  # noqa: E402
    CONF_FAVORITE_ONLY,
    CONF_INCLUDE_HIDDEN,
    CONF_LINK_ID,
    CONF_PAIRING_KEY,
    CONF_SCAN_INTERVAL,
    CONF_VERIFY_SSL,
    CONFIG_ENTRY_MINOR_VERSION,
    CONFIG_ENTRY_VERSION,
    DOMAIN,
)

TEST_LINK_ID = "link_test_pairing"
TEST_PAIRING_KEY = "A" * 43


@pytest.mark.asyncio
async def test_new_entry_gets_server_generated_pairing_credentials(
    hass: HomeAssistant,
    enable_custom_integrations: None,
) -> None:
    """New entries persist credentials generated by the integration."""
    with (
        patch(
            "custom_components.domoticz_sync.config_flow.validate_input",
            AsyncMock(
                return_value={
                    "title": "Domoticz (http://domoticz.test:8080)",
                    "base_url": "http://domoticz.test:8080",
                }
            ),
        ),
        patch(
            "custom_components.domoticz_sync.bridge_credentials.generate_link_id",
            return_value=TEST_LINK_ID,
        ),
        patch(
            "custom_components.domoticz_sync.bridge_credentials.generate_pairing_key",
            return_value=TEST_PAIRING_KEY,
        ),
        patch(
            "custom_components.domoticz_sync.async_setup_entry",
            AsyncMock(return_value=True),
        ),
    ):
        result = await hass.config_entries.flow.async_init(
            DOMAIN,
            context={"source": config_entries.SOURCE_USER},
        )
        result = await hass.config_entries.flow.async_configure(
            result["flow_id"],
            {
                CONF_URL: "http://domoticz.test:8080",
                CONF_USERNAME: "",
                CONF_PASSWORD: "",
                CONF_VERIFY_SSL: False,
            },
        )

    assert result["type"] is FlowResultType.CREATE_ENTRY
    assert DomoticzSyncConfigFlow.VERSION == CONFIG_ENTRY_VERSION
    assert DomoticzSyncConfigFlow.MINOR_VERSION == CONFIG_ENTRY_MINOR_VERSION
    assert result["data"][CONF_LINK_ID] == TEST_LINK_ID
    assert result["data"][CONF_PAIRING_KEY] == TEST_PAIRING_KEY


@pytest.mark.asyncio
async def test_options_show_read_only_pairing_credentials(
    hass: HomeAssistant,
    enable_custom_integrations: None,
) -> None:
    """Open options with credentials and editable values, without writes."""
    entry = MockConfigEntry(
        domain=DOMAIN,
        title="Domoticz test",
        version=CONFIG_ENTRY_VERSION,
        data={
            CONF_URL: "http://domoticz.test:8080",
            CONF_LINK_ID: TEST_LINK_ID,
            CONF_PAIRING_KEY: TEST_PAIRING_KEY,
        },
        options={
            CONF_INCLUDE_HIDDEN: True,
            CONF_FAVORITE_ONLY: True,
            CONF_SCAN_INTERVAL: 45,
        },
    )
    entry.add_to_hass(hass)

    with (
        patch.object(hass.config_entries, "async_update_entry") as update_entry,
        patch.object(
            hass.config_entries,
            "async_reload",
            AsyncMock(),
        ) as reload_entry,
    ):
        result = await hass.config_entries.options.async_init(entry.entry_id)

    assert result["type"] is FlowResultType.FORM
    assert result["description_placeholders"][CONF_LINK_ID] == TEST_LINK_ID
    assert result["description_placeholders"][CONF_PAIRING_KEY] == TEST_PAIRING_KEY
    assert result["data_schema"]({}) == {
        CONF_INCLUDE_HIDDEN: True,
        CONF_FAVORITE_ONLY: True,
        CONF_SCAN_INTERVAL: 45,
    }
    update_entry.assert_not_called()
    reload_entry.assert_not_awaited()

    result = await hass.config_entries.options.async_configure(
        result["flow_id"],
        {
            CONF_INCLUDE_HIDDEN: False,
            CONF_FAVORITE_ONLY: False,
            CONF_SCAN_INTERVAL: 30,
        },
    )

    assert result["type"] is FlowResultType.CREATE_ENTRY
    assert CONF_LINK_ID not in entry.options
    assert CONF_PAIRING_KEY not in entry.options
    assert entry.options == {
        CONF_INCLUDE_HIDDEN: False,
        CONF_FAVORITE_ONLY: False,
        CONF_SCAN_INTERVAL: 30,
    }
    assert entry.data[CONF_LINK_ID] == TEST_LINK_ID
    assert entry.data[CONF_PAIRING_KEY] == TEST_PAIRING_KEY


@pytest.mark.asyncio
async def test_version_one_entry_migrates_pairing_credentials_once(
    hass: HomeAssistant,
) -> None:
    """Migration is stable and never rotates an existing link implicitly."""
    entry = MockConfigEntry(
        domain=DOMAIN,
        title="Domoticz test",
        version=1,
        data={CONF_URL: "http://domoticz.test:8080"},
    )
    entry.add_to_hass(hass)

    with (
        patch(
            "custom_components.domoticz_sync.bridge_credentials.generate_link_id",
            return_value=TEST_LINK_ID,
        ) as generate_link,
        patch(
            "custom_components.domoticz_sync.bridge_credentials.generate_pairing_key",
            return_value=TEST_PAIRING_KEY,
        ) as generate_key,
    ):
        assert await async_migrate_entry(hass, entry)
        assert await async_migrate_entry(hass, entry)

    assert entry.version == CONFIG_ENTRY_VERSION
    assert entry.data[CONF_LINK_ID] == TEST_LINK_ID
    assert entry.data[CONF_PAIRING_KEY] == TEST_PAIRING_KEY
    generate_link.assert_called_once_with()
    generate_key.assert_called_once_with()


@pytest.mark.asyncio
async def test_current_entry_repairs_malformed_string_credentials(
    hass: HomeAssistant,
) -> None:
    """String values still rotate when they violate the wire protocol format."""
    entry = MockConfigEntry(
        domain=DOMAIN,
        title="Domoticz test",
        version=CONFIG_ENTRY_VERSION,
        data={
            CONF_URL: "http://domoticz.test:8080",
            CONF_LINK_ID: "link id with spaces",
            CONF_PAIRING_KEY: "not-a-256-bit-key",
        },
    )
    entry.add_to_hass(hass)

    with (
        patch(
            "custom_components.domoticz_sync.bridge_credentials.generate_link_id",
            return_value=TEST_LINK_ID,
        ) as generate_link,
        patch(
            "custom_components.domoticz_sync.bridge_credentials.generate_pairing_key",
            return_value=TEST_PAIRING_KEY,
        ) as generate_key,
    ):
        assert await async_migrate_entry(hass, entry)

    assert entry.version == CONFIG_ENTRY_VERSION
    assert entry.data[CONF_LINK_ID] == TEST_LINK_ID
    assert entry.data[CONF_PAIRING_KEY] == TEST_PAIRING_KEY
    generate_link.assert_called_once_with()
    generate_key.assert_called_once_with()


@pytest.mark.asyncio
async def test_partial_entry_preserves_valid_link_when_repairing_key(
    hass: HomeAssistant,
) -> None:
    """Repairing one missing field does not rotate the other valid field."""
    entry = MockConfigEntry(
        domain=DOMAIN,
        title="Domoticz test",
        version=1,
        data={
            CONF_URL: "http://domoticz.test:8080",
            CONF_LINK_ID: TEST_LINK_ID,
        },
    )
    entry.add_to_hass(hass)

    with (
        patch(
            "custom_components.domoticz_sync.bridge_credentials.generate_link_id",
        ) as generate_link,
        patch(
            "custom_components.domoticz_sync.bridge_credentials.generate_pairing_key",
            return_value=TEST_PAIRING_KEY,
        ) as generate_key,
    ):
        assert await async_migrate_entry(hass, entry)

    assert entry.version == CONFIG_ENTRY_VERSION
    assert entry.data[CONF_LINK_ID] == TEST_LINK_ID
    assert entry.data[CONF_PAIRING_KEY] == TEST_PAIRING_KEY
    generate_link.assert_not_called()
    generate_key.assert_called_once_with()


@pytest.mark.asyncio
async def test_options_hide_malformed_credentials_without_mutation(
    hass: HomeAssistant,
    enable_custom_integrations: None,
) -> None:
    """The options flow neither displays nor repairs malformed credentials."""
    original_data = {
        CONF_URL: "http://domoticz.test:8080",
        CONF_LINK_ID: [],
        CONF_PAIRING_KEY: "short",
    }
    entry = MockConfigEntry(
        domain=DOMAIN,
        title="Domoticz test",
        version=CONFIG_ENTRY_VERSION,
        data=original_data,
    )
    entry.add_to_hass(hass)

    with (
        patch(
            "custom_components.domoticz_sync.bridge_credentials.generate_link_id",
            return_value=TEST_LINK_ID,
        ) as generate_link,
        patch(
            "custom_components.domoticz_sync.bridge_credentials.generate_pairing_key",
        ) as generate_key,
        patch.object(hass.config_entries, "async_update_entry") as update_entry,
        patch.object(
            hass.config_entries,
            "async_reload",
            AsyncMock(),
        ) as reload_entry,
    ):
        result = await hass.config_entries.options.async_init(entry.entry_id)

    assert result["type"] is FlowResultType.FORM
    assert result["description_placeholders"][CONF_LINK_ID] == "Unavailable"
    assert result["description_placeholders"][CONF_PAIRING_KEY] == "Unavailable"
    assert entry.data == original_data
    generate_link.assert_not_called()
    generate_key.assert_not_called()
    update_entry.assert_not_called()
    reload_entry.assert_not_awaited()


@pytest.mark.parametrize(
    ("version", "minor_version"),
    [
        (CONFIG_ENTRY_VERSION + 1, 0),
        (CONFIG_ENTRY_VERSION, CONFIG_ENTRY_MINOR_VERSION + 1),
    ],
)
@pytest.mark.asyncio
async def test_options_future_entry_credentials_are_never_mutated(
    hass: HomeAssistant,
    enable_custom_integrations: None,
    version: int,
    minor_version: int,
) -> None:
    """Configure treats unknown future credential formats as read-only data."""
    original_data = {
        CONF_URL: "http://domoticz.test:8080",
        CONF_LINK_ID: "future link format",
        CONF_PAIRING_KEY: "future key format",
    }
    entry = MockConfigEntry(
        domain=DOMAIN,
        title="Domoticz test",
        version=version,
        minor_version=minor_version,
        data=original_data,
    )
    entry.add_to_hass(hass)

    with (
        patch(
            "custom_components.domoticz_sync.bridge_credentials.generate_link_id",
        ) as generate_link,
        patch(
            "custom_components.domoticz_sync.bridge_credentials.generate_pairing_key",
        ) as generate_key,
        patch.object(hass.config_entries, "async_update_entry") as update_entry,
        patch.object(
            hass.config_entries,
            "async_reload",
            AsyncMock(),
        ) as reload_entry,
    ):
        result = await hass.config_entries.options.async_init(entry.entry_id)

    assert result["type"] is FlowResultType.FORM
    assert result["description_placeholders"][CONF_LINK_ID] == "Unavailable"
    assert result["description_placeholders"][CONF_PAIRING_KEY] == "Unavailable"
    assert entry.version == version
    assert entry.minor_version == minor_version
    assert entry.data == original_data
    generate_link.assert_not_called()
    generate_key.assert_not_called()
    update_entry.assert_not_called()
    reload_entry.assert_not_awaited()


@pytest.mark.asyncio
async def test_future_entry_version_is_rejected_without_mutation(
    hass: HomeAssistant,
) -> None:
    """Unknown future config formats are never repaired as if they were current."""
    original_data = {
        CONF_URL: "http://domoticz.test:8080",
        CONF_LINK_ID: "future link format",
        CONF_PAIRING_KEY: "future key format",
    }
    entry = MockConfigEntry(
        domain=DOMAIN,
        title="Domoticz test",
        version=CONFIG_ENTRY_VERSION + 1,
        data=original_data,
    )
    entry.add_to_hass(hass)

    with (
        patch(
            "custom_components.domoticz_sync.bridge_credentials.generate_link_id",
        ) as generate_link,
        patch(
            "custom_components.domoticz_sync.bridge_credentials.generate_pairing_key",
        ) as generate_key,
    ):
        assert not await async_migrate_entry(hass, entry)

    assert entry.version == CONFIG_ENTRY_VERSION + 1
    assert entry.data == original_data
    generate_link.assert_not_called()
    generate_key.assert_not_called()


@pytest.mark.asyncio
async def test_future_minor_version_is_rejected_without_mutation(
    hass: HomeAssistant,
) -> None:
    """A newer minor schema is not rewritten by an older integration release."""
    original_data = {
        CONF_URL: "http://domoticz.test:8080",
        CONF_LINK_ID: "future link format",
        CONF_PAIRING_KEY: "future key format",
    }
    entry = MockConfigEntry(
        domain=DOMAIN,
        title="Domoticz test",
        version=CONFIG_ENTRY_VERSION,
        minor_version=CONFIG_ENTRY_MINOR_VERSION + 1,
        data=original_data,
    )
    entry.add_to_hass(hass)

    with (
        patch(
            "custom_components.domoticz_sync.bridge_credentials.generate_link_id",
        ) as generate_link,
        patch(
            "custom_components.domoticz_sync.bridge_credentials.generate_pairing_key",
        ) as generate_key,
    ):
        assert not await async_migrate_entry(hass, entry)

    assert entry.version == CONFIG_ENTRY_VERSION
    assert entry.minor_version == CONFIG_ENTRY_MINOR_VERSION + 1
    assert entry.data == original_data
    generate_link.assert_not_called()
    generate_key.assert_not_called()
